<?php
	$title = 'Campaigning Online';
	include '../../inc/header.php';
?>

<div id="story">

<h2>Campaigning Online: The Internet as Reinforcer, Motivator and Fund-Raiser</h2>
<h4>CCTP 796: Electoral Campaign Communications / April 26, 2004</h4>

<p>As the story goes, former Vermont governor Howard Dean revolutionized the use of the Internet for political campaigning in 2003 and early 2004, employing the medium for everything from converting and mobilizing supporters to (perhaps most importantly) raising unparalleled sums of money. That Dean eventually self-destructed in the primaries &mdash; attributable as much to outside factors as to Dean's campaign itself &mdash; does not underestimate the significance of his contribution to the proverbial political strategic playbook.</p>
<p>In the 2004 presidential campaign season, major-party presidential candidates have employed the Internet to an unprecedented degree to communicate their campaign messages. However, despite the Internet's potential as a means to reach out to undecided or easily swayed voters, the most effective functions of candidate Web sites continue to be 1) soliciting and processing donations online; 2) strengthening and reinforcing existing voter support; 3) mobilizing volunteer efforts; and 4) disseminating campaign messages to the mass media. This paper will focus specifically on the online efforts of the Kerry and Dean presidential campaigns, with occasional mentions of third-party groups, such as the Democratic National Committee and MoveOn.org.</p>

<h3>The Internet Audience</h3>
<p>The Internet often is hailed for its revolutionary potential to further democratize politics, offering unmediated communication between a candidate and his or her potential supporters, adding greater transparency to the political process (for example, the ability to study candidates' Federal Election Commission financial filings; see opensecrets.org) and allowing for a new kind of grassroots political organization and mobilization. Michael Cornfield and Johan Seiger write, &quot;The Internet is best understood, in comparison with other media, as a locus that uniquely combines unlimited consideration and direct response.&quot; [<a href="#1">1</a>] Site visitors have an unlimited amount of time to peruse, absorb, and evaluate political information presented online (as compared to the limited exposure of watching a brief television advertisement) and are able to submit feedback &mdash; in the form of e-mail, campaign contributions, or the like &mdash; directly and immediately to the campaign (without the delay of waiting for mail delivery or for a check to clear).</p>
<p>Particularly important for third-party and &quot;upstart&quot; candidates, but also important to mainstream candidates, is the ability the Internet medium affords for candidates to communicate directly with their audience at minimal cost and with minimal worry about how (or if) their messages might be conveyed through the mass media. &quot;[I]t is not always safe to trust intermediaries to be fare and accurate, and it can be illuminating when candidates present their issues in their own way, with their own choices of emphasis and rhetoric,&quot;  writes Peter Levine. [<a href="#2">2</a>] In a single, easily accessible venue, campaigns can communicate directly with undecided voters, existing supporters, the media, and any other interested groups or individuals who choose to visit the site. And instead of strict one-way communication between leader and audience, visitors to campaign Web sites are, ideally, able to correspond with the candidate and/or his or her campaign organization &mdash; or with each other. At the same time, online communications are often cheaper than direct mail or paid media advertising, and offer the potential for much more immediate response.</p>
<p>According to a February 2004 Nielsen//NetRatings study, [<a href="#3">3</a>] nearly 70 percent of Americans, or 204.3 million people, have some kind of access to the Internet. Demographically, Internet users are more affluent than the general population (and the fastest-growing segment of the Internet population is households with income of $75,000 and up). [<a href="#4">4</a>] These affluent users are more likely to be subscribers to high-speed broadband Internet service, which is more costly than the slower dial-up service. An April 2004 Pew Internet and American Life study found that broadband users are more likely to spend longer periods of time online and to perform a greater variety of online tasks. [<a href="#5">5</a>]</p>
<p>Internet users are more politically active as well: A March 2004 Nielsen//NetRatings study [<a href="#6">6</a>] found that 86 percent of online users are registered voters, and 77 percent voted in the 2000 presidential election, compared to the offline population, where 70 percent are registered and 60 percent voted in 2000. Online users also reported greater participation in offline political activities: 50 percent had signed a political petition, 37 percent had written to an elected official, and 28 percent had donated to a political campaign or organization. And about 25 percent of people age 30 and younger report conducting at least one form of political activity &mdash; be it candidate/issue research, discussion/chat, or the like &mdash; <em>online</em>. [<a href="#7">7</a>] </p>
<p>All of these demographic qualities suggest that the online population, being more likely to show interest and participate in political affairs, is an ideal audience to target for political campaign messages.</p>

<h3>Outreach</h3>
<p>One of the main functions of a candidate Web site is to keep its visitors informed about the latest developments regarding the candidate. A population accustomed to constantly changing online news sites expects that a leading candidate Web site be similarly up-to-date and frequently changing as the campaign goes on. The main feature on the Kerry campaign home page changes on a daily basis, usually related to a campaign event, an issue in the media, or an attack on/response to his opponent. It also has become common for the campaign to prominently release any public disclosures via the Web site, such as Kerry's April 23, 2004, release of medical records from Kerry's time in the Navy. [<a href="#8">8</a>] This is a smart tactic to boost both the visibility and the relevancy of the campaign Web site, and maybe attract a few site visitors who might not otherwise have come to the site, exposing them not only to the information they came for, but to Kerry's overall campaign message as well. For example, it cannot be a coincidence that the first document on the page listing Kerry's medical records [<a href="#9">9</a>] is about the candidate's war medals.</p>
<p>In keeping with today's accelerated news cycle, the campaigns also have taken to attacking and counter-attacking each other via the campaign Web sites. The Kerry site, for instance, has a feature called the &quot;D-Bunker,&quot; [<a href="#10">10</a>] a weblog-style compendium of the Kerry campaign's latest responses to Bush &quot;false statements&quot; and debunkings of &quot;right-wing myths.&quot; (In response, GeorgeWBush.com has a &quot;Kerry Media Center&quot; section with a special &quot;D-Bunker Buster&quot; feature.) Washington Post media critic Howard Kurtz followed the rapid-fire volley/parry of the dueling campaigns in one of his columns:</p>

<blockquote>
<p>Technology and the sheer acceleration of news coverage have combined to produce a presidential campaign that is faster and more frenetic than ever before, reducing response time to mere minutes. Although campaigns have been in rapid response mode since the days of Bill Clinton's 1992 war room, Bush and Kerry operatives now flood reporters with e-mail attacks and BlackBerry responses, arrange conference calls and wage a Web war complete with online video &mdash; a far cry from the faxed statements of an earlier era.</p>
<p>The stakes are considerable. In a campaign that is striking for its early intensity and daily negativity, each side is trying to frame the debate &mdash; Bush by painting Kerry as big on taxes and soft on defense, and Kerry by depicting the president as a failure on the economy and Iraq. Each newspaper headline, television sound bite or Internet posting burnishes or blemishes the candidates' image. [<a href="#11">11</a>]</p>
</blockquote>

<p>It is important to recognize the significance of the interaction between online and traditional media in conveying a campaign message. In this case, these online &quot;debunker&quot; features offer political writers plenty of easy material to cover the back-and-forth volleys of negative campaigning between the two candidates. Mainstream media's covering these online skirmishes provides more exposure for the candidates and for their Web sites (although it is debatable just how <em>useful</em> that exposure, often covered as &quot;campaign color&quot; rather than substance, is in helping the voting public make informed political judgments).</p>
<p>It is important to recognize the Internet as a <em>tool</em> for reaching a broad audience, but should not be employed to the exclusion of traditional media. As Cornfield and Seiger write, &quot;The Internet is not a replacement for television, but it can be, in the hands of an innovative candidate, a substantial, and perhaps decisive, supplement.&quot; [<a href="#12">12</a>] The major political campaigns do not focus their online efforts on voter &quot;conversion&quot; &mdash; winning over undecided voters &mdash; because appealing to potential voters through other media has proven far more effective. Mainstream campaign sites by no means try to exclude potential voters; rather, while these sites do provide candidate and issue information for undecided voters, all-out efforts to attract and convert undecided voters is not the core focus of their online operations.</p>

<table class="datatable" cellpadding="0" cellspacing="0" border="0">
  <tr valign="bottom">
    <th scope="col">Medium</th>
    <th scope="col">All adults<br>(%)</th>
    <th scope="col">All Internet<br>users (%)</th>
    <th scope="col">Go online<br>for election<br>news (%)</th>
  </tr>
  <tr class="shadedrow">
    <td>Television</td>
    <td>66</td>
    <td>62</td>
    <td>50</td>
  </tr>
  <tr>
    <td>- Network</td>
    <td>7</td>
    <td>7</td>
    <td>9</td>
  </tr>
  <tr class="shadedrow">
    <td>- Local</td>
    <td>35</td>
    <td>32</td>
    <td>15</td>
  </tr>
  <tr>
    <td>- Cable</td>
    <td>21</td>
    <td>20</td>
    <td>24</td>
  </tr>
  <tr class="shadedrow">
    <td>Newspapers</td>
    <td>33</td>
    <td>33</td>
    <td>33</td>
  </tr>
  <tr>
    <td>Radio</td>
    <td>13</td>
    <td>14</td>
    <td>12</td>
  </tr>
  <tr class="shadedrow">
    <td>Magazines</td>
    <td>1</td>
    <td>2</td>
    <td>2</td>
  </tr>
  <tr>
    <td>Internet</td>
    <td>7</td>
    <td>11</td>
    <td>31</td>
  </tr>
  <caption><b>Figure 1:</b> &quot;TV Still the Primary Source for Election News.&quot; Percentages may not add up to 100 because respondents were allowed to choose up to two primary information sources. [<a href="#13">13</a>] </caption>
</table>

<p>The influence and audience share of the Internet pales in comparison with that of television and other mainstream media. A Nielsen//NetRatings study found that, in December 2003, 940,000 unique Internet users visited DeanforAmerica.com (Howard Dean's campaign site), and 455,000 visited GeorgeWBush.com. [<a href="#14">14</a>] In comparison, the week of Dec. 8-14, 2003, <i>NBC Nightly News</i> averaged 11.2 million viewers, <i>ABC World News Tonight</i> 10.4 million, and <i>CBS Evening News</i> 8 million. [<a href="#15">15</a>] A January 2003 study [<a href="#16">16</a>] by the Pew Internet and American Life Project and the Pew Research Center found that television remains the public's primary source for election information, claimed by 66 percent of all adults (and 50 percent of politically-interested Internet users).</p>
<p>Given the powerful influence of traditional media, politicians cannot afford not to continue using those media to their utmost advantage in getting their campaign message out to the public. Take, for example, the free-media value of producing a controversial campaign advertisement. The ad itself might air just once. However, through &quot;ad watch&quot; articles and television segments or through other news reports, that ad might then be aired and re-aired, with special attention paid to it. A 2001 study by G.W. Gwiasda of Ohio State University found that such repetition in a &quot;news&quot; context can have a significant impact on the political opinions formed by undecided voters. [<a href="#17">17</a>] As the saying goes, the media &quot;may not be successful much of the time in telling people what to think, but it is stunningly successful in telling its readers what to think <em>about</em>.&quot; [<a href="#18">18</a>]</p>
<p>It is important as well to note the likely audience of a candidate's Web site. With the ever-increasing supply of media outlets and perspectives to choose from, it has become much easier for a citizen to succumb to selectivity bias, tending to consume information from only those outlets whose information and perceived biases fit his or her own. Cass Sunstein calls these ideological groupings &quot;voluntary communities&quot; &mdash; loose groups of people who &quot;organize around a narrow range of interests in which the members are in broad agreement.&quot; [<a href="#19">19</a>] (Take, for example, the heavily conservative skew of FoxNews, which has used its winking nod to objectivity &mdash; &quot;We report, you decide&quot; &mdash; as a coy attempt to market its tailored biases. This is a company that knows the audience it wants to attract, and what that audience wants to hear.) Internet users, being a more politically informed and politically active population to begin with &mdash; and users of Internet political sites to an even greater degree &mdash; may log on with their political views already at least partially formed and focus their attention on sites that address or match their own perspectives. A December 2003 study from Nielsen//NetRatings [<a href="#20">20</a>] found that only a small number of Internet users visited <em>both</em> DeanforAmerica.com and GeorgeWBush.com during the month of December, leading the authors of the report to suggest that the sites' other visitors are coming for reasons other than candidate comparison/deliberation. In other words, campaign Web sites possibly are already are preaching to the converted.</p>
<p>Amid all this fragmentation, a candidate Web site must compete not only against that of its political opponent, but against the Web sites of  various &quot;trusted&quot; media outlets. A 2003 George Washington University/Pew Internet and American Life Project study found that more people than ever &mdash; 73 percent of politically-oriented Internet users &mdash; consulted the Web sites of politically-oriented organizations and issue advocacy groups. [<a href="#21">21</a>] Despite the easy availability of political literature directly from a given campaign, political Internet users often seek out third-party sources &mdash; be they the online sites of offline media companies or the Web sites of issue advocacy groups with whom they identify &mdash; to help them sort through which information is important to them and (if they are still deliberating for whom to vote) help them make their choice.</p>
<p>The authors of the 2003 George Washington University/Pew Internet and American Life Project report concluded that visitors to politically-oriented Web sites come not to be convinced, but rather to have their existing views reinforced. &quot;[O]n the whole, the opinions that the online citizenry possesses when it logs on tend to be reinforced, not altered, by the information it encounters, and the activities it engages in.&quot; [<a href="#22">22</a>] Campaign Web sites, then, realizing that their most frequent visitors likely already are supporters, then work to strengthen that base of support, and possibly channel it into other activities that could benefit the campaign leading up to the voting on Election Day.</p>
<p>One of the simplest roles for a campaign Web site is that of information provider, offering basic information about a candidate and his or her political views. In studying campaign Web sites through 2002, however, Peter Levine found that the information offered often was of little substance:</p>

<blockquote>The sites that I explored presented [issue] information in an abbreviated &mdash; almost coded &mdash; fashion, so as to impress people who already knew where they stood on such complex topics as 'social promotion,' 'a woman's right to choose' (the word abortion is usually omitted), or a 'balanced-budged amendment.' I found few, if any, efforts to explain concepts or to change people's minds. [<a href="#23">23</a>]</blockquote>

<p>The goal, then, is not to educate readers about the nuances of the issues, or of the candidate's own views. Indeed, shorthand keywords arguably might serve as aids in readers' mental issue checklists, and an aid to forming talking points to rationalize their support for the candidate. Nuance might only serve to complicate matters for the campaign and for readers. For example, it likely would confuse potential supporters to explain that John Kerry is pro-choice, yet personally is anti-abortion, and at the same time it might undermine the campaign to have another piece of printed fodder that the Bush campaign can use to demonstrate Kerry's perceived desire to &quot;have it both ways.&quot; Clear-cut messages are far less confusing and less likely to cloud the campaign's overall message.</p>
<p>Organizers of campaign Web sites tend to be very particular about the language they employ and the arrangement/hierarchy of features on a given page. Wording is carefully chosen both to closely mirror the campaign's &quot;theme&quot; and core messages, while, conscious of the interactivity of the medium, calling site visitors to action with task-oriented language. For example, JohnKerry.com uses call-to-action phrases &mdash; such as &quot;Make a Contribution,&quot; &quot;Watch Video,&quot; &quot;Get Informed,&quot; and &quot;Get Infolved&quot; &mdash; for its non-article-related links and section headers. Dean's Web site employed similar language (i.e. &quot;Contribute! Help Take Back Our Country&quot;) enticing users to click on action-oriented links. [<a href="#24">24</a>]</p>
<p>Campaign Web site language also is significant in the way it tries to appeal to visitors and set up expectations about the level and breadth of the candidate's base of support. With phrases such as &quot;Grow the Movement: Double Dean!&quot; and a list of fast-growing cities supporting the candidate, Dean's site in the summer of 2003 suggested to visitors and supporters that they were part of a larger, growing grassroots movement. The site's depiction of its base of support might then influence an individual site visitor's opinion about the campaign and/or his or her place in it. These kind of appeals are reminiscent of Diana Mutz's theory of &quot;impersonal influence:&quot;</p>

<blockquote>To extend Cohen's well-worn maxim, one might say that mass media may not be particularly influential in telling people what to think, or even what to think about, but media are tremendously influential in telling people what others are thinking about and experiencing. These perceptions, in turn, have important consequences for the political behavior of mass publics and political elites as well. [<a href="#25">25</a>]</blockquote>

<p>One's perception of what is important to other people might cause one to re-evaluate one's stance on that issue or individual. A site visitor's influenced belief that he is not the only one to be intrigued by Dean's campaign message might, in turn, lead him to be less cautious in researching or supporting the candidate. People like to feel as if their views are shared, as if they are part of a cohesive group.</p>
<p>Cornfield and Siegel emphasize the importance of campaigns collecting information from their site visitors as well.</p>

<blockquote>[Y[our list of e-mail addresses is a cornerstone of your online campaign: an economical and powerful means of mobilizing volunteers and increasing their ranks ... [P]eople will provide an e-mail address to a campaign as long as they feel they will get something useful in return ... and as long as the terms under which the e-mail address will be used (and shared) are clearly disclosed. [<a href="#26">26</a>]</blockquote>

<p>Keeping in contact with supporters &mdash; but not abusing their interest &mdash; helps reinforce the campaign message, and might strengthen voter support by making those voters feel more actively involved and personally invested with the continuing success of the candidate and the campaign. The more detailed the information that a campaign has about its registered supporters (i.e. issue interests, zip code), the better the campaign can target those supporters as issue-related news and local events come up. Convincing people to sign on may not be too difficult. A January 2004 study by the Pew Internet and American Life Project and the Pew Research Center found that 11 percent of the public (and 18 percent of Internet users) send or receive e-mails about the campaign or candidates. [<a href="#27">27</a>] This number likely will increase as more users rely on the Internet for political research and the mass public's comfort level with the medium grows. And with a greater sense of conviction or personal investment, supporters might be open to appeals to volunteer and/or donate funds to the campaign. And, indeed, campaign e-mail updates usually include further information about actions that individual subscribers can take to support the campaign.</p>
<p>Such voter outreach efforts often can dovetail into appeals for campaign donations. The Dean campaign went so far as to solicit supporters' cellular phone numbers for &quot;Dean Wireless.&quot; Subscribers to &quot;Dean Wireless&quot; would receive text messages with campaign news updates &mdash; as well as appeals for campaign donations that would try to take advantage of any indignation the message might evoke (i.e. &quot;President Bush said &quot;x&quot; about Howard Dean. Donate to the campaign to help bring Bush down!&quot;). Online donations make up an ever-increasing proportion of campaign donations, and while average online donations are smaller than traditional offline donations (Dean averaged about $110 per online donation), the potential quantity of donations received, particularly after an important campaign event (such as a major primary win), and speed at which those donations can be processed cannot be ignored.</p>

<blockquote>[O]nce your campaign has installed an online contribution system, it can dovetail with your e-mail outreach and your Web site promotion, such that the marginal cost of raising money will fall toward zero ... For the time being, the Internet cannot match ... traditional methods in the raw dollar amounts they will raise. But in terms of 'cost per acquisition,' that is, the average number of pennies the campaign must spend to get a donor dollar, the Internet is the most efficient way to raise money. [<a href="#28">28</a>]</blockquote>

<p>Such donation systems are crucial for upstart campaigns whose coffers are often much smaller and more quickly drained than those of their better-funded competitors. And the more that campaigns and the media educate citizens about online donation systems, and the more that campaigns hone their appeals, the more popular online donations may become.</p>
<p>Kerry, meanwhile, has, since being named the de facto Democratic presidential nominee, begun soliciting for campaign donations online via major news Web sites, such as boston.com (The Boston Globe), washingtonpost.com (The Washington Post) and nytimes.com (The New York Times), as well as widely-read political weblogs.  With a humorous appeal &mdash; Kerry, pushed upward by a flood of small donations, tips &quot;King George&quot; off his pile of gold bricks &mdash; the ads are likely to be remembered (and maybe capitalized upon) by viewing demographic that likely already has an interest in political issues. &quot;Regardless of how many people click through and convert, an online ad might help 'brand' the campaign, raising its viewers' awareness of your name and basic message.&quot; [<a href="#29">29</a>]</p>
<p>Political organizations also have begun to employ viral marketing techniques to attract attention. Viral marketing is the online equivalent of word-of-mouth buzz. A message is sent out to a small group of people via e-mail, and then those people forward the message to other like-minded or interested people, and so on, as the message begins to replicate like a virus. These types of campaigns are difficult to control &mdash; a marketer has no way of knowing for sure who will receive the message. The riskier the message, the higher the chance of success, but also the higher the chance of a public relations snafu. Possibly because the potential audience is more culturally savvy or politically aligned and the production costs are far lower, campaigns and political groups are more likely to experiment with riskier or less &quot;formal&quot; online marketing efforts to spread messages and/or solicit donations. The Democratic National Committee has made a regular practice of posting Flash-based political advertisements to its Web site. These animated movies usually take aim at Republican policies or personalities, focus on a particular issue, and employ either humor or scare tactics to convey their message. The most recent such movie, released for Earth Day, sharply criticizes President Bush's environmental record. [<a href="#30">30</a>] Text on the page beneath the movie tries to inspire viewers to action, from discussing &quot;talking points&quot; with friends to familiarizing themselves with Kerry's position on environmental issues. The DNC often e-mails these ads to members of the media as well, hoping to accelerate any &quot;buzz&quot; the ad might generate and broaden the ad's potential audience.</p>
<p>Online appeals for voters to talk to their friends about a given candidate or issue (such as that employed by the DNC &quot;Earth Day ad&quot;) rely heavily on Paul Lazarsfeld's &quot;two-step flow&quot; model of opinion formation. Lazarsfeld's model posits that &quot;ideas often flow from [media sources] and print to the opinion leaders and from them to the less active sections of the population.&quot; [<a href="#31">31</a>] In this case, campaign supporters, having gotten their &quot;talking points&quot; from the campaign, serve as &quot;opinion leaders,&quot; educating and politically influencing friends or acquaintances who are less politically informed and whose political opinions are less-fully formed. Lazarzfeld's research, while it underestimated the significance of media effects, found that interpersonal interactions played a strong role in opinion formation. &quot;[P]eople who made up their minds later in the campaign were more likely to mention personal influences in explaining how they formed their final vote decision.&quot; [<a href="#32">32</a>] Personal appeals from trusted friends or acquaintances (or authority figures) can carry an important psychological weight, and sometimes can make a difference in voter conversion.</p>
<p>Speaking to an entirely different audience, the Internet is a boon for campaigns in communicating directly with mainstream media outlets. The more coverage the media provide of a candidate &mdash; <em>free</em> media, exposure the campaign did not have to pay for &mdash; the higher the candidate's public visibility. Most high-profile campaign Web sites have media-oriented sections, featuring the latest press releases, disclosure statements and the like. Dean campaign chairman Joe Trippi took an unorthodox route in mid-2003 to help pull Dean, then largely an unknown on the national stage, into the mainstream media spotlight. Cornfield and Siegler write:</p>

<blockquote>The big change involving the Internet and media politics has less to do with who the key opinion leaders are than with what their opinions are likely to be about. There has been a significant increase in the number and range of available sources for opinion-relevant information. There is, additionally, a greater incentive to draw from this cyber-well because the opinion leaders/media stars must file more frequently. Consequently, the roster of story topics on the mythical agenda that the media do so much to set has been greatly expanded. It is easier to get a fresh take, a blurb about a new group, etc., onto the digital agenda, where insiders will see it. However, it is harder to stay visible there for long and to break through to the crowded and diffused mass media agenda. [<a href="#33">33</a>]</blockquote>

<p>Trippi appealed to the political weblog community, hoping to build an online &quot;buzz&quot; around the candidate. Many &quot;offline&quot; political media figures read political weblogs, keeping themselves in tune with trends and murmurings on the Internet. Once the blog community began writing about Dean, mainstream media political writers began to take notice. And a myth was born.</p>

<h3>The Internet and Howard Dean</h3>
<p>Part of Dean's success lay in the close connection Dean's campaign was able to forge between the candidate (or the &quot;image&quot; of the candidate) and those supporters who found and followed his campaign online. Important as well, given the personality-driven nature of modern campaigns, were the campaign trail &quot;angry Howard&quot; persona that Dean developed and the way that this personality was integrated into the campaign Web site DeanforAmerica.com. In part because of the novelty of the Dean campaign's online strategy (which then became an integral part of his media &quot;storyline&quot;) and the strong public &quot;cult of personality&quot; that developed around him, Dean arguably became inextricably linked in the public mind with his campaign Web site (to which he occasionally contributed blog entries) and his online following &mdash; ironic, perhaps, considering that Dean himself had only limited personal involvement with the campaign's online operations. [<a href="#34">34</a>] The language employed by the Dean campaign (the notion of a growing &quot;movement&quot;), the candidate's forceful personality, and the campaign's novel approach toward organizing supporters online may have contributed to supporters forming a stronger sense of personal investment with the candidate and his Web site than had occurred with other campaigns, whose Web presences were rather more impersonal. Mutz writes, &quot;As interactions have become increasingly impersonal, people have taken even greater pains to cultivate impressions of a highly personal community.&quot; [<a href="#35">35</a>] The <em>appearance</em> of a strong online community, and the constant references in the media to Dean having one, may also have contributed to this perception of the Dean Web presence.</p>
<p>In contrast, JohnKerry.com, which adopted many of the ballyhooed online &quot;innovations&quot; pioneered by the Dean campaign when the site relaunched in late summer 2003 (to coincide with Kerry's official presidential candidacy announcement), thus far has failed to cultivate a similar sense of candidate personality and personal investment in the campaign's online presence and surrounding community. Kerry's site does include a campaign weblog (as does GeorgeWBush.com), but it is updated by Kerry staff and supporters, with no personal contributions from Kerry himself. The site also has posted a number of John Kerry computer desktop backgrounds for visitors to download. The images are not all of the best quality, and images such as Kerry with an electric guitar, with the words &quot;Kerry Rocks!&quot;, seem like undignified put-ons. The campaign appears to be trying to create an online cult of personality for a candidate who, at least according to the media storyline/stereotype, does not have one. And between the candidate personality differences and the completely different role of the Web site in the campaign.</p>
<p>The Dean campaign, by virtue of its early media strategy, also made strong efforts in &quot;coalitional politics&quot; [<a href="#36">36</a>] &mdash; reaching out to other online organizations and Web sites whose members and audience might appreciate Dean's message. The online networking seemed to further entrench the Dean campaign in the online world. The Kerry Web site does not seem to have such strong ties to online groups, but rather to the traditional &quot;real world&quot; interest groups.</p>
<p>One key difference between the Dean campaign and other campaigns was the manner in which it organized volunteers and supporters. Rather than coordinating all volunteer activities and gatherings, the campaign made a point of letting the volunteers organize themselves and their own &quot;Support Dean&quot; events. The strategy suggested a measure of trust in the campaign's supporters, while opening the campaign up to a significant danger in allowing supporters to organize independently,  risking public relations snafus and possibly unwelcome diversions from the campaign's core message. One of the core weaknesses of the Dean campaign, however, was that it had no message, or else that its message was too indistinct to be easily remembered.</p>
<p>In addition to being the new media fringe candidate, Dean distinguished himself by being the loudest and the angriest and the most anti-Bush candidate in the race. Supporters responded to his anger, until concerns about his electability &mdash; the likelihood of Dean winning the presidency in a campaign against Bush &mdash; began to arise in the media. Mutz writes, &quot;[A] person who bases his or her selection on strategic considerations will try to assess likely winners and losers by gauging the opinions of others in order to make a vote decision.&quot; [<a href="#37">37</a>] With Democratic voters' priority this election season uncharacteristically on <em>winning</em> rather than on <em>issues</em>, strategy won out over emotional/philosophical kinship.</p>
<p>Another Dean weakness may have been that he was <em>too</em> closely tied to his online constituency, either believing in the ascendant myths being painted by media coverage or badly misjudging the amount of attention that his campaign would have to give to traditional forms of campaigning and voter outreach. Cornfield and Seiger remind readers, &quot;...circulation in the digital age depends on a timely combination of e-mail, telephone, and face-to-face contact, a fusion of high-tech and high-touch.&quot; [<a href="#38">38</a>] The Internet is an increasingly vital campaign tool, but in a national campaign, it cannot be the only (or most strongly used) tool.</p>

<hr>

<div id="endnotes">

<h3>Endnotes</h3>

<ol>
<li><a name="1"></a>Cornfield, Michael and Johan Seiger. &quot;The Net and the Nomination.&quot; <i>The Making of the Presidential Candidates 2004</i>. Ed. William G. Mayer. Lanham, Md.: Rowman & Littlefield Publishers, Inc., 2004. p. 203.</li>
<li><a name="2"></a>Levine, Peter. &quot;Online Campaigning and the Public Interest.&quot; <i>The Civic Web: Online Politics and Democratic Values</i>. Ed. David M. Anderson and Michael Cornfield. Lanham, Md.: Rowman & Littlefield Publishers, Inc., 2003. pp. 49.</li>
<li><a name="3"></a>&quot;Three Out of Four Americans Have Access to the Internet, According to Nielsen//NetRatings.&quot; Nielsen//NetRatings. 18 March 2004. <<a href="http://www.nielsen-netratings.com/pr/pr_040318.pdf">http://www.nielsen-netratings.com/pr/pr_040318.pdf</a>></li>
<li><a name="4"></a>&quot;Affluent Americans Power Internet Growth, According to Nielsen//NetRatings.&quot; Nielsen//NetRatings. 19 April 2004. <http://www.nielsen-netratings.com/pr/pr_040419.pdf></li>
<li><a name="5"></a>&quot;Broadband Penetration on the Upswing.&quot; Pew Internet and American Life Project. 19 April 2004. <<a href="http://www.pewinternet.org/reports/toc.asp?Report=120">http://www.pewinternet.org/reports/toc.asp?Report=120</a>></li>
<li><a name="6"></a>&quot;Web Surfers Are More Politically Active Than General Population, According to Nielsen//NetRatings.&quot; Nielsen//NetRatings. 19 March 2004. <<a href="http://www.nielsen-netratings.com/pr/pr_040319.pdf">http://www.nielsen-netratings.com/pr/pr_040319.pdf</a>></li>
<li><a name="7"></a>&quot;Cable and Internet Loom Large in Fragmented Political News Universe &mdash; Perceptions of Partisan Bias Seen as Growing &mdash; Especially by Democrats.&quot; Pew Internet and American Life Project and the Pew Research Center. 11 Jan. 2004. <<a href="http://www.pewinternet.org/reports/toc.asp?Report=110">http://www.pewinternet.org/reports/toc.asp?Report=110</a>></li>
<li><a name="8"></a>See <<a href="http://www.johnkerry.com/pressroom/releases/pr_2004_0423b.html">http://www.johnkerry.com/pressroom/releases/pr_2004_0423b.html</a>></li>
<li><a name="9"></a>See <<a href="http://www.johnkerry.com/about/military_records.html">http://www.johnkerry.com/about/military_records.html</a>></li>
<li><a name="10"></a>See <<a href="http://blog.johnkerry.com/dbunker/">http://blog.johnkerry.com/dbunker/</a>></li>
<li><a name="11"></a>Kurtz, Howard. &quot;Campaign Mantra Is Rapid Response.&quot; <i>The Washington Post.</i> 20 March 2004. A06. <<a href="http://www.washingtonpost.com/ac2/wp-dyn?pagename=article&node=&contentId=A9216-2004Mar19">http://www.washingtonpost.com/ac2/wp-dyn?pagename=article&node=&contentId=A9216-2004Mar19</a>></li>
<li><a name="12"></a>Cornfield, Michael and Johan Seiger. &quot;The Net and the Nomination.&quot; <i>The Making of the Presidential Candidates 2004</i>. Ed. William G. Mayer. Lanham, Md.: Rowman & Littlefield Publishers, Inc., 2004. p. 201.</li>
<li><a name="13"></a>&quot;Political Sites Gain, But Major News Sites Still Dominant.&quot; The Pew Research Center for the People and the Press.&quot; 5 Jan. 2003. <<a href="http://people-press.org/reports/display.php3?ReportID=169">http://people-press.org/reports/display.php3?ReportID=169</a>><br />
<br />
<i>See also:</i> &quot;Modest Increase in Internet Use for Campaign 2002.&quot; Pew Internet and American Life Project. 5 Jan. 203. <<a href="http://www.pewinternet.org/reports/toc.asp?Report=82">http://www.pewinternet.org/reports/toc.asp?Report=82</a>></li>
<li><a name="14"></a>&quot;More than One Million People Visit DeanforAmerica.com and GeorgeWBush.com, Making Them the Most Visited Presidential Candidate Sites, According to Nielsen//NetRatings.&quot; Nielsen//NetRatings. 21 Jan. 2004. <<a href="http://www.nielsen-netratings.com/pr/pr_040121_us.pdf">http://www.nielsen-netratings.com/pr/pr_040121_us.pdf</a>><br />
<br />
A December 2003 comScore study reported 605,000 unique visitors to DeanforAmerica.com, 503,000 to GeorgeWBush.com, and 316,000 to JohnKerry.com. &quot;Political Web Sites Have a Significant Impact on Americans’ Pre-Election Attitudes and Behaviors, comScore Reports.&quot; comScore. 28 Jan. 2004. <<a href="http://www.comscore.com/press/release.asp?press=414">http://www.comscore.com/press/release.asp?press=414</a>><br />
<br />
Neither Nielsen//NetRatings nor comScore has publicly reported recent Internet usage data for Bush or Kerry’s Web sites.</li>
<li><a name="15"></a>Bauder, David. &quot;'Survivor' Shows It's Still Reality Champ.&quot; Associated Press. 16 Dec. 2004. <<a href="http://www.miami.com/mld/miamiherald/entertainment/7506192.htm?1c">http://www.miami.com/mld/miamiherald/entertainment/7506192.htm?1c</a>><br />
<br />
The most recent network nightly news viewership numbers are roughly similar. The week of April 12-18, 2004, <i>NBC Nightly News</i> averaged 10 million viewers, <i>ABC World News Tonight</i> 9.1 million, and <i>CBS Evening News</i> 7.2 million. Bauder, David. &quot;NBC Scores Trump-Inspired Ratings Win.&quot; Associated Press. 20 April 2004. <<a href="http://customwire.ap.org/dynamic/stories/N/NIELSENS">http://customwire.ap.org/dynamic/stories/N/NIELSENS</a>></li>
<li><a name="16"></a>&quot;Political Sites Gain, But Major News Sites Still Dominant.&quot; The Pew Research Center for the People and the Press.&quot; 5 Jan. 2003. <<a href="http://people-press.org/reports/display.php3?ReportID=169">http://people-press.org/reports/display.php3?ReportID=169</a>><br />
<br />
<i>See also:</i> &quot;Modest Increase in Internet Use for Campaign 2002.&quot; Pew Internet and American Life Project. 5 Jan. 203. <<a href="http://www.pewinternet.org/reports/toc.asp?Report=82">http://www.pewinternet.org/reports/toc.asp?Report=82</a>></li>
<li><a name="17"></a>Gwiasda studied network news coverage of the &quot;Willie Horton&quot; attack ad the George H.W. Bush campaign sponsored against Michael Dukakis during the 1988 presidential campaign.
<blockquote>Results show that general campaign coverage of race and crime issues as well as coverage of Horton influenced individual ideological perceptions of Dukakis ... media coverage affects individuals with moderate levels of political awareness who have weaker initial predispositions. Combined, these results demonstrate that media can exert both significantly and substantively significant influence on the public.</blockquote>
Gwiasda, G.W. &quot;Network News Coverage of Campaign Advertisements: Media's Ability to Reinforce Campaign Messages.&quot; <i>American Politics Research</i>. Sept. 2001, Vol. 29, No. 5. pp. 461-482.</li>
<li><a name="18"></a>Cohen, Bernard C. quoted in McCombs, Maxwell E. and Donald L. Shaw. &quot;The Agenda-Setting Function of Mass Media.&quot; <i>Public Opinion Quarterly</i> Volume 36, Issue 2 (Summer 1972), pp. 176-187.</li>
<li><a name="19"></a>Galston, William A.. &quot;Political Fragmentation Is the Problem.&quot; <i>The Civic Web: Online Politics and Democratic Values</i>. Ed. David M. Anderson and Michael Cornfield. Lanham, Md.: Rowman & Littlefield Publishers, Inc., 2003. pp. 37.</li>
<li><a name="20"></a>&quot;More than One Million People Visit DeanforAmerica.com and GeorgeWBush.com, Making Them the Most Visited Presidential Candidate Sites, According to Nielsen//NetRatings.&quot; Nielsen//NetRatings. 21 Jan. 2004. <<a href="http://www.nielsen-netratings.com/pr/pr_040121_us.pdf">http://www.nielsen-netratings.com/pr/pr_040121_us.pdf</a>></li>
<li><a name="21"></a>&quot;Untuned Keyboards: Online Campaigners, Citizens, and Portals in the 2002 Elections.&quot; Pew Internet and American Life Project. 20 March 2003. <<a href="http://www.pewinternet.org/reports/toc.asp?Report=85">http://www.pewinternet.org/reports/toc.asp?Report=85</a>></li>
<li><a name="22"></a>&quot;Untuned Keyboards: Online Campaigners, Citizens, and Portals in the 2002 Elections.&quot; Pew Internet and American Life Project. 20 March 2003. <<a href="http://www.pewinternet.org/reports/toc.asp?Report=85">http://www.pewinternet.org/reports/toc.asp?Report=85</a>></li>
<li><a name="23"></a>Levine, Peter. &quot;Online Campaigning and the Public Interest.&quot; <i>The Civic Web: Online Politics and Democratic Values</i>. Ed. David M. Anderson and Michael Cornfield. Lanham, Md.: Rowman & Littlefield Publishers, Inc., 2003. pp. 48.</li>
<li><a name="24"></a>The use of action-oriented terms for site links is a guideline sometimes offered by Internet usability experts for all Web sites. The goal is to help guide users to the information or tasks they came to the site to find.</li>
<li><a name="25"></a>Mutz, Diana. <i>Impersonal Influence: How Perceptions of Mass Collectives Affect Political Attitudes</i>. Cambridge, U.K.: Cambridge University Press, 1998. pp. 5.</li>
<li><a name="26"></a>Cornfield, Michael and Johan Seiger. &quot;The Net and the Nomination.&quot; <i>The Making of the Presidential Candidates 2004</i>. Ed. William G. Mayer. Lanham, Md.: Rowman & Littlefield Publishers, Inc., 2004. pp. 203-4.</li>
<li><a name="27"></a>&quot;Cable and Internet Loom Large in Fragmented Political News Universe &mdash; Perceptions of Partisan Bias Seen as Growing &mdash; Especially by Democrats.&quot; Pew Internet and American Life Project and the Pew Research Center. 11 Jan. 2004. <<a href="http://www.pewinternet.org/reports/toc.asp?Report=110">http://www.pewinternet.org/reports/toc.asp?Report=110</a>></li>
<li><a name="28"></a>Cornfield, Michael and Johan Seiger. &quot;The Net and the Nomination.&quot; <i>The Making of the Presidential Candidates 2004</i>. Ed. William G. Mayer. Lanham, Md.: Rowman & Littlefield Publishers, Inc., 2004. p. 204.</li>
<li><a name="29"></a>Cornfield, Michael and Johan Seiger. &quot;The Net and the Nomination.&quot; <i>The Making of the Presidential Candidates 2004</i>. Ed. William G. Mayer. Lanham, Md.: Rowman & Littlefield Publishers, Inc., 2004. p. 220.</li>
<li><a name="30"></a>See <<a href="http://www.democrats.org/environment/earth_day/">http://www.democrats.org/environment/earth_day/index.html</a>></li>
<li><a name="31"></a>Granted, Lazarsfeld, in his book, downplayed the influence of media effects in political opinion formation, but his findings regarding the effects of personal influence on voting decisions are no less interesting. Lazarsfeld, Paul F., Bernard Berelson, and Hazel Gaudet. <i>The People's Choice: How the Voter Makes Up His Mind in a Presidential Campaign.</i> New York: Cambridge University Press, 1948. pp. 150-158.</li>
<li><a name="32"></a>Lazarsfeld, Paul F., Bernard Berelson, and Hazel Gaudet. <i>The People's Choice: How the Voter Makes Up His Mind in a Presidential Campaign</i>. New York: Cambridge University Press, 1948. pp. 150.</li>
<li><a name="33"></a>Cornfield, Michael and Johan Seiger. &quot;The Net and the Nomination.&quot; <i>The Making of the Presidential Candidates 2004</i>. Ed. William G. Mayer. Lanham, Md.: Rowman & Littlefield Publishers, Inc., 2004. p. 216.</li>
<li><a name="34"></a>Dean's director of Internet outreach, Zephyr Teachout, told CNet News.com that Dean did not get involved with the daily operations of the campaign Web site. McCullagh, Declan. &quot;The Cyberbrains behind Howard Dean.&quot; CNet News.com. 16 Jan. 2004. <<a href="http://news.com.com/2008-1028-5142066.html">http://news.com.com/2008-1028-5142066.html</a>></li>
<li><a name="35"></a>Mutz, Diana. <i>Impersonal Influence: How Perceptions of Mass Collectives Affect Political Attitudes</i>. Cambridge, U.K.: Cambridge University Press, 1998. pp. 29.</li>
<li><a name="36"></a>Cornfield, Michael and Johan Seiger. &quot;The Net and the Nomination.&quot; <i>The Making of the Presidential Candidates 2004</i>. Ed. William G. Mayer. Lanham, Md.: Rowman & Littlefield Publishers, Inc., 2004. p. 206.</li>
<li>Mutz, Diana. <i>Impersonal Influence: How Perceptions of Mass Collectives Affect Political Attitudes</i>. Cambridge, U.K.: Cambridge University Press, 1998. pp. 10.</li>
<li>Cornfield, Michael and Johan Seiger. &quot;The Net and the Nomination.&quot; <i>The Making of the Presidential Candidates 2004</i>. Ed. William G. Mayer. Lanham, Md.: Rowman & Littlefield Publishers, Inc., 2004. p. 214.</li>
</ol>
</div>

</div>

<p><a href="index.php">More writing samples &raquo;</a></p>

<?php
	include '../../inc/footer.php';
?>